services:
  - type: web
    name: scraping-backend
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "python backend/run.py"
    envVars:
      - key: PORT
        value: 10000
    region: frankfurt